// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-N2DO4O8tFSOqD1iVpNxN97WDSfWdz7s',
    appId: '1:680187664629:web:fb9716eb6a13be9141cdbc',
    messagingSenderId: '680187664629',
    projectId: 'agrobizz-6dd59',
    authDomain: 'agrobizz-6dd59.firebaseapp.com',
    storageBucket: 'agrobizz-6dd59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLYoeYdzpDjzYSXg9S1WhNVanULAkiPk',
    appId: '1:680187664629:android:432629da19567d9941cdbc',
    messagingSenderId: '680187664629',
    projectId: 'agrobizz-6dd59',
    storageBucket: 'agrobizz-6dd59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_UKZhFfmtmbne6NQicObCZIKBVg_JDJM',
    appId: '1:680187664629:ios:666b6f3696ef1eb241cdbc',
    messagingSenderId: '680187664629',
    projectId: 'agrobizz-6dd59',
    storageBucket: 'agrobizz-6dd59.appspot.com',
    iosBundleId: 'com.example.farmco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_UKZhFfmtmbne6NQicObCZIKBVg_JDJM',
    appId: '1:680187664629:ios:666b6f3696ef1eb241cdbc',
    messagingSenderId: '680187664629',
    projectId: 'agrobizz-6dd59',
    storageBucket: 'agrobizz-6dd59.appspot.com',
    iosBundleId: 'com.example.farmco',
  );
}
